"""
Divisional Level Railway Admin Routes for IMBPS.
Handles ML optimization generation (Weekly & Monthly),
retrospective history, block improvisation (edit with audit badge),
and section-level block authorization / dispatching to Section Engineers.
"""

from typing import Optional, Dict, Any, List
from fastapi import APIRouter, HTTPException, Query
from app.database import db_manager
from app.ml_bridge import ml_bridge
from app.models import EditBlockRequest, AuthorizeBlockRequest, BatchAuthorizeRequest

router = APIRouter(prefix="/api/divisional", tags=["Divisional Admin"])

@router.post("/optimize-monthly")
def generate_monthly_optimization(
    division: str = Query("Asansol (ASN)", description="Division Name")
):
    """
    Triggers ML-driven Monthly Maintenance Block Optimization using CP-SAT solver.
    """
    plan = ml_bridge.optimize_plan(horizon="MONTHLY", division=division)
    return plan

@router.post("/optimize-weekly")
def generate_weekly_optimization(
    division: str = Query("Asansol (ASN)", description="Division Name")
):
    """
    Triggers ML-driven Weekly Maintenance Block Optimization using CP-SAT solver.
    """
    plan = ml_bridge.optimize_plan(horizon="WEEKLY", division=division)
    return plan

@router.get("/blocks-ahead")
def get_blocks_ahead_for_authorization(
    division: Optional[str] = "Asansol (ASN)"
):
    """
    Retrieves the 1-week ahead maintenance block schedule generated by the ML model.
    Ready for divisional officer review, improvisation (edit), and authorization.
    """
    blocks = db_manager.get_divisional_blocks_state()
    filtered = []
    if not division or division == "ALL":
        filtered = blocks
    else:
        from app.ml_bridge import resolve_division_info, is_matching_division, is_section_in_division
        code, name, _, target_sections = resolve_division_info(division)
        for b in blocks:
            b_div = str(b.get("division", ""))
            b_code = str(b.get("division_code", ""))
            b_sec = str(b.get("section", ""))
            if is_matching_division(b_code, b_div, code, name) and is_section_in_division(b_sec, code, target_sections):
                filtered.append(b)
    return {
        "division": division,
        "count": len(filtered),
        "blocks": filtered
    }

@router.post("/edit-block")
def edit_block_schedule(payload: EditBlockRequest, edited_by: Optional[str] = "Divisional Operations Officer"):
    """
    Divisional officer improvises date, times, duration, line, equipment, or notes.
    Marks the record with an explicit 'EDITED BY DIVISIONAL OFFICER' tag.
    """
    updated = db_manager.edit_block(
        block_id=payload.block_id,
        edit_data=payload.model_dump(exclude_unset=True),
        edited_by=edited_by or "Divisional Officer"
    )
    if not updated:
        raise HTTPException(status_code=404, detail=f"Block {payload.block_id} not found.")

    return {
        "status": "SUCCESS",
        "message": f"Block {payload.block_id} successfully updated and marked as EDITED.",
        "block": updated
    }

@router.post("/authorize-block")
def authorize_block(payload: AuthorizeBlockRequest, authorized_by: Optional[str] = "Divisional Operations Manager"):
    """
    Authorizes the block and dispatches it directly to the designated Section Engineer
    for that department (TMS / SMMS / TDMS).
    """
    updated = db_manager.authorize_block(
        block_id=payload.block_id,
        authorized_by=authorized_by or "Divisional Operations Manager (DOM)"
    )
    if not updated:
        raise HTTPException(status_code=404, detail=f"Block {payload.block_id} not found.")

    return {
        "status": "SUCCESS",
        "message": f"Block {payload.block_id} authorized. Transmitted to Section Engineer {updated.get('assigned_to')}.",
        "block": updated
    }

@router.post("/authorize-all")
def authorize_all_blocks(payload: BatchAuthorizeRequest, authorized_by: Optional[str] = "Divisional Operations Manager"):
    """Authorizes all pending blocks in batch."""
    updated_blocks = db_manager.authorize_all_blocks(
        authorized_by=authorized_by or "Divisional Operations Manager (DOM)"
    )
    return {
        "status": "SUCCESS",
        "message": f"All {len(updated_blocks)} blocks authorized and dispatched to departmental Section Engineers.",
        "blocks": updated_blocks
    }

@router.get("/maintenance-history")
def get_divisional_maintenance_history(
    division: str = Query("Asansol (ASN)"),
    timeframe: str = Query("all", description="previous_week, previous_month, or all"),
    department: Optional[str] = None,
    limit: int = 100
):
    """
    Returns divisional maintenance history archives for previous week and previous month.
    """
    history = db_manager.get_maintenance_history(
        dept=department,
        division=division,
        limit=limit
    )
    return {
        "division": division,
        "timeframe": timeframe,
        "count": len(history),
        "history": history
    }
